name: 'mydjango'

# The language and version for your app.
type: 'python 3.10'

# Global dependencies to be added and cached and then available as commands.
dependencies:
    python:
        runtime/runtime: '^3.10'

# The app's relationships (connections) with services or other applications.
# The key is the relationship name that can be viewed in the app.
# The value is specific to how the service is configured.
relationships:
    postgresql_database: "database1:postgresql"

# Scripts that are run as part of the build and deploy process.
hooks:
    # Build hooks can modify app files on disk but not access any services like databases.
    build: ./build.sh
    # Deploy hooks can access services but the file system is now read-only.
    deploy: ./deploy.sh
    # Post deploy hooks run when the app is accepting outside requests.
    post_deploy: ./post_deploy.sh

# The size of the app's persistent disk (in MB).
disk: 2048

# Define writable, persistent filesystem mounts.
# The key is the directory path relative to the application root.
# In this case, `web-files` is just a unique name for the mount.
mounts:
    'web/files':
        source: local
        source_path: 'web-files'

# The app's configuration when it's exposed to the web.
web:
    locations:
        '/':
            # The app's public directory relative to its root.
            root: 'public'
            # A front controller to determine how to handle requests.
            passthru: '/app.pyhon'
        # Allow uploaded files to be served, but don't run scripts.
        # Missing files get sent to the front controller.
        '/files':
            root: 'web/files'
            scripts: false
            allow: true
            passthru: '/app.python'
          operations:
     RUNTIME_OPERATION_NAME:
     role: USER_ROLE
     commands:
     operations:
    manual-migration:
    role: admin
    commands:
    start: python manage.py manual_migration  start: COMMAND
    commands:
    start: python server.py