"https://www.master-7rqtwti-p2kvz64xudm46.us.platformsh.site.

.":
    type: upstream
    upstream: "app:http"
"https://www.master-7rqtwti-p2kvz64xudm46.us.platformsh.site.

.":
    type: upstream
    upstream: "api:http"
"https://www.master-7rqtwti-p2kvz64xudm46.us.platformsh.site.

./ws":
    type: upstream
    upstream: "ws-app:http"
    cache:
        enabled: false
